export const exampleAirports = [
  {
    name: "A Coruna Airport",
    iata_code: "LCG",
    icao_code: "LECO",
    lat: 43.30206,
    lng: -8.37726,
    country_code: "ES",
  },
  {
    name: "Ablitas",
    iata_code: null,
    icao_code: "LETU",
    lat: 42.00838,
    lng: -1.62303,
    country_code: "ES",
  },
  {
    name: "Adeje Heliport",
    iata_code: null,
    icao_code: "GCAD",
    lat: 28.124165,
    lng: -16.742906,
    country_code: "ES",
  },
  {
    name: "Adolfo Suarez Madrid-Barajas Airport",
    iata_code: "MAD",
    icao_code: "LEMD",
    lat: 40.49181,
    lng: -3.56948,
    country_code: "ES",
  },
  {
    name: "Aeródromo de Guadalupe",
    iata_code: null,
    icao_code: "LEGU",
    lat: 39.345699,
    lng: -5.19735,
    country_code: "ES",
  },
  {
    name: "Aeródromo de Herrera de Pisuerga",
    iata_code: null,
    icao_code: "LERP",
    lat: 42.5923,
    lng: -4.2902,
    country_code: "ES",
  },
  {
    name: "Aeródromo de los Oteros",
    iata_code: null,
    icao_code: "LEOS",
    lat: 42.333056,
    lng: -5.451944,
    country_code: "ES",
  },
  {
    name: "Aeródromo Requena El Rebollar",
    iata_code: null,
    icao_code: "LERE",
    lat: 39.474701,
    lng: -1.03444,
    country_code: "ES",
  },
  {
    name: "Aeródromo Virgen de La Estrella",
    iata_code: null,
    icao_code: "LEVE",
    lat: 38.4205555556,
    lng: -6.3569444444,
    country_code: "ES",
  },
  {
    name: "Aeroport de Girona - Costa Brava",
    iata_code: "GRO",
    icao_code: "LEGE",
    lat: 41.90097,
    lng: 2.76055,
    country_code: "ES",
  },
  {
    name: "Agoncillo",
    iata_code: null,
    icao_code: "LELO",
    lat: 42.454167,
    lng: -2.320833,
    country_code: "ES",
  },
  {
    name: "Albacete Airport",
    iata_code: "ABC",
    icao_code: "LEAB",
    lat: 38.94853,
    lng: -1.86352,
    country_code: "ES",
  },
  {
    name: "Alcantarilla Air Base",
    iata_code: null,
    icao_code: "LERI",
    lat: 37.95239,
    lng: -1.23103,
    country_code: "ES",
  },
  {
    name: "Alcoba de Los Montes Heliport",
    iata_code: null,
    icao_code: "LENT",
    lat: 39.267248,
    lng: -4.490408,
    country_code: "ES",
  },
  {
    name: "Alcorcón Hospital Heliport",
    iata_code: null,
    icao_code: "LEHA",
    lat: 40.349702,
    lng: -3.83819,
    country_code: "ES",
  },
  {
    name: "Alcorisa Forestry Heliport",
    iata_code: null,
    icao_code: "LEAF",
    lat: 40.898141,
    lng: -0.396393,
    country_code: "ES",
  },
  {
    name: "Alfes",
    iata_code: null,
    icao_code: "LEAT",
    lat: 41.54702,
    lng: 0.65438,
    country_code: "ES",
  },
  {
    name: "Algeciras Heliport",
    iata_code: "AEI",
    icao_code: "LEAG",
    lat: 36.12881,
    lng: -5.44107,
    country_code: "ES",
  },
  {
    name: "Alhama De Murcia Airfield",
    iata_code: null,
    icao_code: "LELH",
    lat: 37.748901,
    lng: -1.30216,
    country_code: "ES",
  },
  {
    name: "Alicante-Elche Airport",
    iata_code: "ALC",
    icao_code: "LEAL",
    lat: 38.28217,
    lng: -0.55816,
    country_code: "ES",
  },
  {
    name: "Almagro Heliport",
    iata_code: null,
    icao_code: "LEAO",
    lat: 38.95083,
    lng: -3.74084,
    country_code: "ES",
  },
  {
    name: "Almansa",
    iata_code: null,
    icao_code: "LELM",
    lat: 38.89517,
    lng: -1.11368,
    country_code: "ES",
  },
  {
    name: "Almeria Airport",
    iata_code: "LEI",
    icao_code: "LEAM",
    lat: 36.84394,
    lng: -2.3701,
    country_code: "ES",
  },
  {
    name: "Altarejos-Guadalcanal Private Airfield",
    iata_code: null,
    icao_code: "LEGC",
    lat: 38.1717,
    lng: -5.73953,
    country_code: "ES",
  },
  {
    name: "Alvaro Cunqueiro Hospital Helipad.",
    iata_code: null,
    icao_code: "LEHV",
    lat: 42.187797,
    lng: -8.714093,
    country_code: "ES",
  },
  {
    name: "Ampuriabrava",
    iata_code: null,
    icao_code: "LEAP",
    lat: 42.26,
    lng: 3.10972,
    country_code: "ES",
  },
  {
    name: "Andorra - La Seu d'Urgell Airport",
    iata_code: "LEU",
    icao_code: "LESU",
    lat: 42.3386,
    lng: 1.40917,
    country_code: "ES",
  },
  {
    name: "Armilla Air Base",
    iata_code: null,
    icao_code: "LEGA",
    lat: 37.133202,
    lng: -3.63569,
    country_code: "ES",
  },
  {
    name: "Asturias Airport",
    iata_code: "OVD",
    icao_code: "LEAS",
    lat: 43.56357,
    lng: -6.03462,
    country_code: "ES",
  },
  {
    name: "Autoridad Portuaria de Barcelona Heliport",
    iata_code: null,
    icao_code: "LEPB",
    lat: 41.3642997742,
    lng: 2.1830101013,
    country_code: "ES",
  },
  {
    name: "Badajoz Airport",
    iata_code: "BJZ",
    icao_code: "LEBZ",
    lat: 38.89125,
    lng: -6.82133,
    country_code: "ES",
  },
  {
    name: "Barcelona-El Prat Airport",
    iata_code: "BCN",
    icao_code: "LEBL",
    lat: 41.29708,
    lng: 2.07846,
    country_code: "ES",
  },
  {
    name: "BARDENAS REALES (MET)",
    iata_code: null,
    icao_code: "LEBR",
    lat: 42.192778,
    lng: -1.459722,
    country_code: "ES",
  },
  {
    name: "Basa Aerea de Valencia Betera",
    iata_code: null,
    icao_code: "LEBT",
    lat: 39.62447,
    lng: -0.472576,
    country_code: "ES",
  },
  {
    name: "Base Aérea de Colmenar Viejo",
    iata_code: null,
    icao_code: "LECV",
    lat: 40.697296,
    lng: -3.763255,
    country_code: "ES",
  },
  {
    name: "Beas De Segura",
    iata_code: null,
    icao_code: "LEBE",
    lat: 38.27128,
    lng: -2.94709,
    country_code: "ES",
  },
  {
    name: "Benabarre",
    iata_code: null,
    icao_code: "LENA",
    lat: 42.02214,
    lng: 0.4818,
    country_code: "ES",
  },
  {
    name: "Berga Heliport",
    iata_code: null,
    icao_code: "LERG",
    lat: 42.104811,
    lng: 1.85812,
    country_code: "ES",
  },
  {
    name: "Bilbao Bus Station",
    iata_code: "BFB",
    icao_code: null,
    lat: 43.260921,
    lng: -2.949244,
    country_code: "ES",
  },
  {
    name: "Bilbao Airport",
    iata_code: "BIO",
    icao_code: "LEBB",
    lat: 43.3011,
    lng: -2.91061,
    country_code: "ES",
  },
  {
    name: "BP Oil España Heliport",
    iata_code: null,
    icao_code: "LEBP",
    lat: 39.957901,
    lng: -0.011632,
    country_code: "ES",
  },
  {
    name: "Burgos Villafria Airport",
    iata_code: "RGS",
    icao_code: "LEBG",
    lat: 42.35763,
    lng: -3.62076,
    country_code: "ES",
  },
  {
    name: "Bustarviejo Heliport",
    iata_code: null,
    icao_code: "LEBU",
    lat: 40.856922,
    lng: -3.742135,
    country_code: "ES",
  },
  {
    name: "Cala'n Blanes Heliport",
    iata_code: null,
    icao_code: "LENB",
    lat: 39.996836,
    lng: 3.814097,
    country_code: "ES",
  },
  {
    name: "Calaf-Sallavinera Airfield",
    iata_code: null,
    icao_code: "LECF",
    lat: 41.744202,
    lng: 1.55694,
    country_code: "ES",
  },
  {
    name: "Campo Gaviota Heliport",
    iata_code: null,
    icao_code: "LEGV",
    lat: 43.4416999817,
    lng: -2.7536098957,
    country_code: "ES",
  },
  {
    name: "Campolara",
    iata_code: null,
    icao_code: "LECX",
    lat: 40.8998,
    lng: -4.51965,
    country_code: "ES",
  },
  {
    name: "Can Bonastre Wine Resort Heliport",
    iata_code: null,
    icao_code: "LEBS",
    lat: 41.507695,
    lng: 1.787712,
    country_code: "ES",
  },
  {
    name: "Cas Curredó Heliport",
    iata_code: null,
    icao_code: "LECC",
    lat: 38.9291,
    lng: 1.46633,
    country_code: "ES",
  },
  {
    name: "Casarrubios Del Monte",
    iata_code: null,
    icao_code: "LEMT",
    lat: 40.23481,
    lng: -4.0272,
    country_code: "ES",
  },
  {
    name: "Casas de los Pinos Airfield",
    iata_code: null,
    icao_code: "LEPI",
    lat: 39.298199,
    lng: -2.37872,
    country_code: "ES",
  },
  {
    name: "Castejón de los Monegros Airport",
    iata_code: null,
    icao_code: "LECJ",
    lat: 41.60779953,
    lng: -0.2183270007,
    country_code: "ES",
  },
  {
    name: "CASTEJON DE MONEGROS (HUESCA)",
    iata_code: null,
    icao_code: "LECJ",
    lat: 41.607778,
    lng: -0.218611,
    country_code: "ES",
  },
  {
    name: "Castellon-Costa Azahar Airport",
    iata_code: "CDT",
    icao_code: "LEDS",
    lat: 40.2097,
    lng: 0.06972,
    country_code: "ES",
  },
  {
    name: "Castellon de la Plana Airport",
    iata_code: null,
    icao_code: "LECN",
    lat: 39.99902,
    lng: 0.02618,
    country_code: "ES",
  },
  {
    name: "Ceuta",
    iata_code: "JCU",
    icao_code: "GECE",
    lat: 35.88902,
    lng: -5.34636,
    country_code: "ES",
  },
  {
    name: "CEUTA (HEL MILITAR)",
    iata_code: null,
    icao_code: "GECT",
    lat: 35.888889,
    lng: -5.346389,
    country_code: "ES",
  },
  {
    name: "Ceuta Heliport",
    iata_code: "JCU",
    icao_code: "GECE",
    lat: 35.89207,
    lng: -5.30631,
    country_code: "ES",
  },
  {
    name: "Ceuta Military Heliport",
    iata_code: null,
    icao_code: "GECT",
    lat: 35.889018,
    lng: -5.346354,
    country_code: "ES",
  },
  {
    name: "Ciudad Real Central Airport",
    iata_code: "CQM",
    icao_code: "LERL",
    lat: 38.85856,
    lng: -3.97602,
    country_code: "ES",
  },
  {
    name: "Cordoba Airport",
    iata_code: "ODB",
    icao_code: "LEBA",
    lat: 37.84201,
    lng: -4.84888,
    country_code: "ES",
  },
  {
    name: "Córdoba-Villarrubia Airfield",
    iata_code: null,
    icao_code: "LEDE",
    lat: 37.836632,
    lng: -4.896426,
    country_code: "ES",
  },
  {
    name: "Costa Brava-Centro Heliport",
    iata_code: null,
    icao_code: "LEBC",
    lat: 41.8077011108,
    lng: 3.0371799469,
    country_code: "ES",
  },
  {
    name: "Costa Norte-Puerto de Viveiro-Celeiro Heliport",
    iata_code: null,
    icao_code: "LEPV",
    lat: 43.674801,
    lng: -7.59523,
    country_code: "ES",
  },
  {
    name: "Cueto Firefighting Heliport",
    iata_code: null,
    icao_code: "LEET",
    lat: 42.632898,
    lng: -6.648556,
    country_code: "ES",
  },
  {
    name: "Dirección General de Tráfico Heliport",
    iata_code: null,
    icao_code: "LEDG",
    lat: 40.4492988586,
    lng: -3.6461305618,
    country_code: "ES",
  },
  {
    name: "[Duplicate] Aerodel",
    iata_code: null,
    icao_code: "LEDE",
    lat: 37.836632,
    lng: -4.896426,
    country_code: "ES",
  },
  {
    name: "E. Castellanos-Villacastín Airfield",
    iata_code: null,
    icao_code: "LEEV",
    lat: 40.783901,
    lng: -4.46278,
    country_code: "ES",
  },
  {
    name: "El Berriel Aeroc Airport",
    iata_code: null,
    icao_code: "GCLB",
    lat: 27.782499,
    lng: -15.5072,
    country_code: "ES",
  },
  {
    name: "El Bodon Heliport",
    iata_code: null,
    icao_code: "LEBD",
    lat: 40.48453,
    lng: -6.57709,
    country_code: "ES",
  },
  {
    name: "El Carrascal",
    iata_code: null,
    icao_code: "LEVB",
    lat: 41.82397,
    lng: -4.89375,
    country_code: "ES",
  },
  {
    name: "El Castaño Airfield",
    iata_code: null,
    icao_code: "LECT",
    lat: 39.013604,
    lng: -4.387141,
    country_code: "ES",
  },
  {
    name: "El Copero",
    iata_code: null,
    icao_code: "LEEC",
    lat: 37.31308,
    lng: -5.99907,
    country_code: "ES",
  },
  {
    name: "El Hierro Airport",
    iata_code: "VDE",
    icao_code: "GCHI",
    lat: 27.81485,
    lng: -17.88706,
    country_code: "ES",
  },
  {
    name: "El Manantío Airfield",
    iata_code: null,
    icao_code: "LEEM",
    lat: 38.777508,
    lng: -6.991124,
    country_code: "ES",
  },
  {
    name: "El Musel Heliport",
    iata_code: null,
    icao_code: "LEEL",
    lat: 43.5497322083,
    lng: -5.6954455376,
    country_code: "ES",
  },
  {
    name: "El Portinyol Heliport",
    iata_code: null,
    icao_code: "LEPY",
    lat: 41.5834999084,
    lng: 2.560790062,
    country_code: "ES",
  },
  {
    name: "El Pueyo de Jaca Heliport",
    iata_code: null,
    icao_code: "LEPJ",
    lat: 42.716444,
    lng: -0.300132,
    country_code: "ES",
  },
  {
    name: "El Tietar",
    iata_code: null,
    icao_code: "LETI",
    lat: 40.24773,
    lng: -4.78943,
    country_code: "ES",
  },
  {
    name: "Estacion de Autobuses Benidorm",
    iata_code: "BBF",
    icao_code: null,
    lat: 38.549444,
    lng: -0.125,
    country_code: "ES",
  },
  {
    name: "Federico Garcia Lorca Airport",
    iata_code: "GRX",
    icao_code: "LEGR",
    lat: 37.18873,
    lng: -3.77736,
    country_code: "ES",
  },
  {
    name: "Fira M2 Heliport",
    iata_code: null,
    icao_code: "LEFR",
    lat: 41.3539009094,
    lng: 2.1291699409,
    country_code: "ES",
  },
  {
    name: "Fuentemilanos",
    iata_code: null,
    icao_code: "LEFM",
    lat: 40.88804,
    lng: -4.23896,
    country_code: "ES",
  },
  {
    name: "Fuerteventura Airport",
    iata_code: "FUE",
    icao_code: "GCFV",
    lat: 28.45272,
    lng: -13.86376,
    country_code: "ES",
  },
  {
    name: "Garidells Heliport",
    iata_code: null,
    icao_code: "LEGD",
    lat: 41.2139015198,
    lng: 1.2415599823,
    country_code: "ES",
  },
  {
    name: "Garray",
    iata_code: null,
    icao_code: "LEGY",
    lat: 41.82124,
    lng: -2.47934,
    country_code: "ES",
  },
  {
    name: "Gran Canaria Airport",
    iata_code: "LPA",
    icao_code: "GCLP",
    lat: 27.93189,
    lng: -15.38659,
    country_code: "ES",
  },
  {
    name: "Guttmann Hospital Heliport",
    iata_code: null,
    icao_code: "LEJL",
    lat: 41.479645,
    lng: 2.238493,
    country_code: "ES",
  },
  {
    name: "Heli Montsiá - Amposta Heliport",
    iata_code: null,
    icao_code: "LEMN",
    lat: 40.6664009094,
    lng: 0.5647220016,
    country_code: "ES",
  },
  {
    name: "Helicsa Heliport",
    iata_code: null,
    icao_code: "LEHE",
    lat: 39.071106,
    lng: -1.834567,
    country_code: "ES",
  },
  {
    name: "Henares Hospital Heliport",
    iata_code: null,
    icao_code: "LEHH",
    lat: 40.419524,
    lng: -3.532319,
    country_code: "ES",
  },
  {
    name: "Hospital Can Misses Heliport",
    iata_code: null,
    icao_code: "LENM",
    lat: 38.9175,
    lng: 1.41944,
    country_code: "ES",
  },
  {
    name: "Hospital Doce de Octubre Heliport",
    iata_code: null,
    icao_code: "LEDO",
    lat: 40.3747362789,
    lng: -3.6998525262,
    country_code: "ES",
  },
  {
    name: "Hospital Doctor Josep Trueta Heliport",
    iata_code: null,
    icao_code: "LEJT",
    lat: 41.9978981018,
    lng: 2.8213999271,
    country_code: "ES",
  },
  {
    name: "Hospital General De Catalunya Heliport",
    iata_code: null,
    icao_code: "LEHG",
    lat: 41.4735984802,
    lng: 2.0425000191,
    country_code: "ES",
  },
  {
    name: "Hospital General De Manresa Heliport",
    iata_code: null,
    icao_code: "LEHM",
    lat: 41.7200012207,
    lng: 1.8405599594,
    country_code: "ES",
  },
  {
    name: "Hospital San Pau Heliport",
    iata_code: null,
    icao_code: "LESP",
    lat: 41.4135017395,
    lng: 2.1719601154,
    country_code: "ES",
  },
  {
    name: "HOSPITAL UNIVERSITARIO DE BELLVITGE (BARCELONA)(HEL)",
    iata_code: null,
    icao_code: "LEHB",
    lat: 41.345833,
    lng: 2.108056,
    country_code: "ES",
  },
  {
    name: "Hospital Universitario De Canarias Heliport",
    iata_code: null,
    icao_code: "GCHU",
    lat: 28.4562,
    lng: -16.292101,
    country_code: "ES",
  },
  {
    name: "Hospital Universitario Joan XXIII Heliport",
    iata_code: null,
    icao_code: "LEHJ",
    lat: 41.1255989075,
    lng: 1.2381299734,
    country_code: "ES",
  },
  {
    name: "Hotel Rey Juan Carlos I Heliport",
    iata_code: null,
    icao_code: "LEJC",
    lat: 41.3824996948,
    lng: 2.10916996,
    country_code: "ES",
  },
  {
    name: "Huesca-Pirineos Airport",
    iata_code: "HSK",
    icao_code: "LEHC",
    lat: 42.08093,
    lng: -0.32347,
    country_code: "ES",
  },
  {
    name: "Ibiza Airport",
    iata_code: "IBZ",
    icao_code: "LEIB",
    lat: 38.87286,
    lng: 1.37312,
    country_code: "ES",
  },
  {
    name: "IES La Guancha Heliport",
    iata_code: null,
    icao_code: "GCLG",
    lat: 28.377407,
    lng: -16.649328,
    country_code: "ES",
  },
  {
    name: "Igualada/Odena Airfield",
    iata_code: null,
    icao_code: "LEIG",
    lat: 41.585602,
    lng: 1.65306,
    country_code: "ES",
  },
  {
    name: "Infanta Leonor University Hospital Heliport",
    iata_code: null,
    icao_code: "LELV",
    lat: 40.386565,
    lng: -3.615839,
    country_code: "ES",
  },
  {
    name: "Insular Hospital Helipad",
    iata_code: null,
    icao_code: "GCHG",
    lat: 28.082835,
    lng: -15.417392,
    country_code: "ES",
  },
  {
    name: "Iurreta Heliport",
    iata_code: null,
    icao_code: "LEIU",
    lat: 43.1819000244,
    lng: -2.6463899612,
    country_code: "ES",
  },
  {
    name: "Jerez Airport",
    iata_code: "XRY",
    icao_code: "LEJR",
    lat: 36.74462,
    lng: -6.06011,
    country_code: "ES",
  },
  {
    name: "King Juan Carlos Hospital Heliport",
    iata_code: null,
    icao_code: "LERY",
    lat: 40.340433,
    lng: -3.86951,
    country_code: "ES",
  },
  {
    name: "La Atalaya Firefighting Heliport",
    iata_code: null,
    icao_code: "LEAY",
    lat: 38.634316,
    lng: -3.789527,
    country_code: "ES",
  },
  {
    name: "La Axarquía-Leoni Benabu Airfield",
    iata_code: null,
    icao_code: "LEAX",
    lat: 36.801666,
    lng: -4.135556,
    country_code: "ES",
  },
  {
    name: "La Cabrera Heliport",
    iata_code: null,
    icao_code: "LEER",
    lat: 40.855353,
    lng: -3.617942,
    country_code: "ES",
  },
  {
    name: "La Calderera",
    iata_code: null,
    icao_code: "LELA",
    lat: 38.7479,
    lng: -3.51463,
    country_code: "ES",
  },
  {
    name: "La Caminera Airfield",
    iata_code: null,
    icao_code: "LENE",
    lat: 38.669727,
    lng: -3.303194,
    country_code: "ES",
  },
  {
    name: "La Cartuja (Expo 92) Heliport",
    iata_code: null,
    icao_code: "LEEX",
    lat: 37.3993,
    lng: -6.010675,
    country_code: "ES",
  },
  {
    name: "La Centenera",
    iata_code: null,
    icao_code: "LENN",
    lat: 38.11489,
    lng: -4.11547,
    country_code: "ES",
  },
  {
    name: "La Cerdanya Airfield",
    iata_code: null,
    icao_code: "LECD",
    lat: 42.386398,
    lng: 1.86667,
    country_code: "ES",
  },
  {
    name: "La Gomera Airport",
    iata_code: "GMZ",
    icao_code: "GCGM",
    lat: 28.02987,
    lng: -17.21455,
    country_code: "ES",
  },
  {
    name: "La Juliana",
    iata_code: null,
    icao_code: "LEJU",
    lat: 37.29541,
    lng: -6.16326,
    country_code: "ES",
  },
  {
    name: "La Mancha-Toledo Airfield",
    iata_code: null,
    icao_code: "LEMX",
    lat: 39.562099,
    lng: -3.25075,
    country_code: "ES",
  },
  {
    name: "La Morgal",
    iata_code: null,
    icao_code: "LEMR",
    lat: 43.43048,
    lng: -5.82691,
    country_code: "ES",
  },
  {
    name: "La Nava - Corral De Ayllón Airfield",
    iata_code: null,
    icao_code: "LECA",
    lat: 41.410801,
    lng: -3.44833,
    country_code: "ES",
  },
  {
    name: "La Palma Airport",
    iata_code: "SPC",
    icao_code: "GCLA",
    lat: 28.62648,
    lng: -17.75561,
    country_code: "ES",
  },
  {
    name: "La Perdiz - Torre De Juan Abad Airfield",
    iata_code: null,
    icao_code: "LEIZ",
    lat: 38.5131,
    lng: -3.36433,
    country_code: "ES",
  },
  {
    name: "Lanzarote Airport",
    iata_code: "ACE",
    icao_code: "GCRR",
    lat: 28.95027,
    lng: -13.60556,
    country_code: "ES",
  },
  {
    name: "Leon Airport",
    iata_code: "LEN",
    icao_code: "LELN",
    lat: 42.589,
    lng: -5.65556,
    country_code: "ES",
  },
  {
    name: "Lillo",
    iata_code: null,
    icao_code: "LELT",
    lat: 39.71707,
    lng: -3.32064,
    country_code: "ES",
  },
  {
    name: "Lleida-Alguaire Airport",
    iata_code: "ILD",
    icao_code: "LEDA",
    lat: 41.72889,
    lng: 0.53775,
    country_code: "ES",
  },
  {
    name: "Logrono-Agoncillo Airport",
    iata_code: "RJL",
    icao_code: "LERJ",
    lat: 42.45731,
    lng: -2.31627,
    country_code: "ES",
  },
  {
    name: "Los Martínez Del Puerto Airfield",
    iata_code: null,
    icao_code: "LEMP",
    lat: 37.836817,
    lng: -1.097667,
    country_code: "ES",
  },
  {
    name: "Los Pozuelos De Calatrava Airfield",
    iata_code: null,
    icao_code: "LEPZ",
    lat: 38.912201,
    lng: -4.19111,
    country_code: "ES",
  },
  {
    name: "Los Rodeos Army Heliport",
    iata_code: null,
    icao_code: "GCXM",
    lat: 28.483836,
    lng: -16.351263,
    country_code: "ES",
  },
  {
    name: "Lozoyuela Heliport",
    iata_code: null,
    icao_code: "LEZO",
    lat: 40.93602,
    lng: -3.62504,
    country_code: "ES",
  },
  {
    name: "Madrid-Cuatro Vientos Airport",
    iata_code: null,
    icao_code: "LECU",
    lat: 40.37068,
    lng: -3.78514,
    country_code: "ES",
  },
  {
    name: "Madrid-Cuatro Vientos Airport",
    iata_code: "QYU",
    icao_code: "LECU",
    lat: 40.37068,
    lng: -3.78514,
    country_code: "ES",
  },
  {
    name: "MADRID/CUATRO VIENTOS (MIL)",
    iata_code: null,
    icao_code: "LEVS",
    lat: 40.370556,
    lng: -3.785278,
    country_code: "ES",
  },
  {
    name: "Madrid / Getafe",
    iata_code: null,
    icao_code: "LEGT",
    lat: 40.29414,
    lng: -3.72383,
    country_code: "ES",
  },
  {
    name: "Madrid-Torrejon Airport",
    iata_code: "TOJ",
    icao_code: "LETO",
    lat: 40.49675,
    lng: -3.44587,
    country_code: "ES",
  },
  {
    name: "Madrigalejo Del Monte",
    iata_code: null,
    icao_code: "LEJO",
    lat: 42.13432,
    lng: -3.73154,
    country_code: "ES",
  },
  {
    name: "Mafé - Gibraleón Airfield",
    iata_code: null,
    icao_code: "LEMF",
    lat: 37.3643,
    lng: -6.92094,
    country_code: "ES",
  },
  {
    name: "Malaga Airport",
    iata_code: "AGP",
    icao_code: "LEMG",
    lat: 36.6749,
    lng: -4.49911,
    country_code: "ES",
  },
  {
    name: "Manresa Airfield",
    iata_code: null,
    icao_code: "LEMS",
    lat: 41.765301,
    lng: 1.86167,
    country_code: "ES",
  },
  {
    name: "Mas Passamaner Heliport",
    iata_code: null,
    icao_code: "LEPS",
    lat: 41.1859016418,
    lng: 1.1599199772,
    country_code: "ES",
  },
  {
    name: "MASPALOMAS (ESTACION ESPACIAL)",
    iata_code: null,
    icao_code: "GCMP",
    lat: 27.7375,
    lng: -15.603056,
    country_code: "ES",
  },
  {
    name: "Maspalomas Station Heliport",
    iata_code: null,
    icao_code: "GCMP",
    lat: 27.765637,
    lng: -15.635286,
    country_code: "ES",
  },
  {
    name: "Matilla De Los Caños Airfield",
    iata_code: null,
    icao_code: "LETC",
    lat: 41.530602,
    lng: -4.925,
    country_code: "ES",
  },
  {
    name: "Melilla Airport",
    iata_code: "MLN",
    icao_code: "GEML",
    lat: 35.27982,
    lng: -2.95626,
    country_code: "ES",
  },
  {
    name: "MELILLA (HEL MILITAR)",
    iata_code: null,
    icao_code: "GEHM",
    lat: 35.280278,
    lng: -2.958056,
    country_code: "ES",
  },
  {
    name: "Menorca Airport",
    iata_code: "MAH",
    icao_code: "LEMH",
    lat: 39.8626,
    lng: 4.21865,
    country_code: "ES",
  },
  {
    name: "Morante",
    iata_code: null,
    icao_code: "LETE",
    lat: 39.03655,
    lng: -6.6901,
    country_code: "ES",
  },
  {
    name: "Moron Air Base",
    iata_code: "OZP",
    icao_code: "LEMO",
    lat: 37.17492,
    lng: -5.61594,
    country_code: "ES",
  },
  {
    name: "Muchamiel",
    iata_code: null,
    icao_code: "LEMU",
    lat: 38.44053,
    lng: -0.47519,
    country_code: "ES",
  },
  {
    name: "Murcia-San Javier Airport",
    iata_code: "MJV",
    icao_code: "LELC",
    lat: 37.77497,
    lng: -0.81239,
    country_code: "ES",
  },
  {
    name: "Naval Station Rota",
    iata_code: "ROZ",
    icao_code: "LERT",
    lat: 36.64205,
    lng: -6.34769,
    country_code: "ES",
  },
  {
    name: "Nou Hospital De Mataró Heliport",
    iata_code: null,
    icao_code: "LENH",
    lat: 41.560798645,
    lng: 2.4297199249,
    country_code: "ES",
  },
  {
    name: "Nuestra Señora de Candelaria University Hospital Helipad",
    iata_code: null,
    icao_code: "GCDC",
    lat: 28.448687,
    lng: -16.28462,
    country_code: "ES",
  },
  {
    name: "Ocaña Airfield",
    iata_code: null,
    icao_code: "LEOC",
    lat: 39.9375,
    lng: -3.50333,
    country_code: "ES",
  },
  {
    name: "Ontur",
    iata_code: null,
    icao_code: "LEOT",
    lat: 38.61733,
    lng: -1.52622,
    country_code: "ES",
  },
  {
    name: "Oviedo Hospital Heliport",
    iata_code: null,
    icao_code: "LEHU",
    lat: 43.37721,
    lng: -5.82638,
    country_code: "ES",
  },
  {
    name: "Palma de Mallorca Airport",
    iata_code: "PMI",
    icao_code: "LEPA",
    lat: 39.55,
    lng: 2.73333,
    country_code: "ES",
  },
  {
    name: "Palma del Río Airfield",
    iata_code: null,
    icao_code: "LEPR",
    lat: 37.714384,
    lng: -5.215226,
    country_code: "ES",
  },
  {
    name: "PALMA/SON SAN JUAN (MIL)",
    iata_code: null,
    icao_code: "LESJ",
    lat: 39.551667,
    lng: 2.738889,
    country_code: "ES",
  },
  {
    name: "Pamplona Airport",
    iata_code: "PNA",
    icao_code: "LEPP",
    lat: 42.77004,
    lng: -1.64633,
    country_code: "ES",
  },
  {
    name: "Parque De Bomberos De Orriols Heliport",
    iata_code: null,
    icao_code: "LEOR",
    lat: 42.1321983337,
    lng: 2.9038898945,
    country_code: "ES",
  },
  {
    name: "Parque De Garraf-Sitges Heliport",
    iata_code: null,
    icao_code: "LEGS",
    lat: 41.2738990784,
    lng: 1.9147200584,
    country_code: "ES",
  },
  {
    name: "Pollenca Seaplane Base",
    iata_code: null,
    icao_code: "LEPO",
    lat: 39.90774,
    lng: 3.10141,
    country_code: "ES",
  },
  {
    name: "Puntagorda Heliport",
    iata_code: null,
    icao_code: "GCPU",
    lat: 28.77882,
    lng: -17.9957,
    country_code: "ES",
  },
  {
    name: "Queimadelos Heliport",
    iata_code: null,
    icao_code: "LEQE",
    lat: 42.215543,
    lng: -8.426442,
    country_code: "ES",
  },
  {
    name: "R.A.C.C. Heliport",
    iata_code: null,
    icao_code: "LERA",
    lat: 41.3833007813,
    lng: 2.1083300114,
    country_code: "ES",
  },
  {
    name: "Rabanal del Camino Firefighting Heliport",
    iata_code: null,
    icao_code: "LERB",
    lat: 42.480863,
    lng: -6.272399,
    country_code: "ES",
  },
  {
    name: "Real Aeroclub de Mahon Menorca",
    iata_code: null,
    icao_code: "LESL",
    lat: 39.86548,
    lng: 4.2539,
    country_code: "ES",
  },
  {
    name: "Region de Murcia International Airport",
    iata_code: "RMU",
    icao_code: "LEMI",
    lat: 37.80507,
    lng: -1.12636,
    country_code: "ES",
  },
  {
    name: "Regional Emergency Center Heliport",
    iata_code: null,
    icao_code: "LELB",
    lat: 40.475232,
    lng: -2.383516,
    country_code: "ES",
  },
  {
    name: "Reus Emergency Center Heliport",
    iata_code: null,
    icao_code: "LECE",
    lat: 41.133698,
    lng: 1.187351,
    country_code: "ES",
  },
  {
    name: "Reus Airport",
    iata_code: "REU",
    icao_code: "LERS",
    lat: 41.14739,
    lng: 1.16717,
    country_code: "ES",
  },
  {
    name: "Robledillo De Mohernando",
    iata_code: null,
    icao_code: "LERM",
    lat: 40.86483,
    lng: -3.2475,
    country_code: "ES",
  },
  {
    name: "Rozas",
    iata_code: null,
    icao_code: "LERO",
    lat: 43.11601,
    lng: -7.4636,
    country_code: "ES",
  },
  {
    name: "S'Arangi Heliport",
    iata_code: null,
    icao_code: "LEME",
    lat: 39.968221,
    lng: 4.093734,
    country_code: "ES",
  },
  {
    name: "Sabadell Airport",
    iata_code: "QSA",
    icao_code: "LELL",
    lat: 41.52097,
    lng: 2.10519,
    country_code: "ES",
  },
  {
    name: "Sabadell Police Heliport",
    iata_code: null,
    icao_code: "LEXE",
    lat: 41.553818,
    lng: 2.066398,
    country_code: "ES",
  },
  {
    name: "Salamanca Airport",
    iata_code: "SLM",
    icao_code: "LESA",
    lat: 40.95212,
    lng: -5.50199,
    country_code: "ES",
  },
  {
    name: "San Enrique",
    iata_code: null,
    icao_code: "LESE",
    lat: 38.73113,
    lng: -4.31347,
    country_code: "ES",
  },
  {
    name: "San Martin Firefighting Heliport",
    iata_code: null,
    icao_code: "LEDV",
    lat: 40.357728,
    lng: -4.376101,
    country_code: "ES",
  },
  {
    name: "San Sebastián de La Gomera Heliport",
    iata_code: null,
    icao_code: "GCGO",
    lat: 28.0972,
    lng: -17.1024,
    country_code: "ES",
  },
  {
    name: "San Sebastian Airport",
    iata_code: "EAS",
    icao_code: "LESO",
    lat: 43.35652,
    lng: -1.79061,
    country_code: "ES",
  },
  {
    name: "SANGUESA (NAVARRA)",
    iata_code: null,
    icao_code: "LESG",
    lat: 42.566667,
    lng: -1.283333,
    country_code: "ES",
  },
  {
    name: "Sant Joan de Reus University Hospital Heliport.",
    iata_code: null,
    icao_code: "LEJN",
    lat: 41.144641,
    lng: 1.12506,
    country_code: "ES",
  },
  {
    name: "Sant Martí De Sescorts Heliport",
    iata_code: null,
    icao_code: "LETM",
    lat: 42.015499115,
    lng: 2.3192501068,
    country_code: "ES",
  },
  {
    name: "Santa Cilia De Jaca",
    iata_code: null,
    icao_code: "LECI",
    lat: 42.56972,
    lng: -0.72778,
    country_code: "ES",
  },
  {
    name: "Santander Airport",
    iata_code: "SDR",
    icao_code: "LEXJ",
    lat: 43.4272,
    lng: -3.82335,
    country_code: "ES",
  },
  {
    name: "Santiago de Compostela Airport",
    iata_code: "SCQ",
    icao_code: "LEST",
    lat: 42.89766,
    lng: -8.41793,
    country_code: "ES",
  },
  {
    name: "Santo Tome Del Puerto",
    iata_code: null,
    icao_code: "LETP",
    lat: 41.20476,
    lng: -3.5956,
    country_code: "ES",
  },
  {
    name: "Servei D'Evacuació Del Circuit De Catalunya Heliport",
    iata_code: null,
    icao_code: "LERV",
    lat: 41.571999,
    lng: 2.26203,
    country_code: "ES",
  },
  {
    name: "Servei Generals Del Circuit De Catalunya Heliport",
    iata_code: null,
    icao_code: "LETA",
    lat: 41.5740013123,
    lng: 2.2571599483,
    country_code: "ES",
  },
  {
    name: "Seville San Pablo Airport",
    iata_code: "SVQ",
    icao_code: "LEZL",
    lat: 37.418,
    lng: -5.89311,
    country_code: "ES",
  },
  {
    name: "Son Bonet Aerodrome",
    iata_code: null,
    icao_code: "LESB",
    lat: 39.59885,
    lng: 2.70278,
    country_code: "ES",
  },
  {
    name: "Sotos",
    iata_code: null,
    icao_code: "LESS",
    lat: 40.20338,
    lng: -2.14369,
    country_code: "ES",
  },
  {
    name: "Tabuyo del Monte Firefighting Heliport",
    iata_code: null,
    icao_code: "LETB",
    lat: 42.295518,
    lng: -6.214514,
    country_code: "ES",
  },
  {
    name: "Talavera de la Reina Heliport",
    iata_code: null,
    icao_code: "LEEI",
    lat: 39.924064,
    lng: -4.801274,
    country_code: "ES",
  },
  {
    name: "Teknon Medical Center Heliport",
    iata_code: null,
    icao_code: "LETK",
    lat: 41.406624,
    lng: 2.127997,
    country_code: "ES",
  },
  {
    name: "Tenerife North Airport",
    iata_code: "TFN",
    icao_code: "GCXO",
    lat: 28.48265,
    lng: -16.34154,
    country_code: "ES",
  },
  {
    name: "Tenerife South Airport",
    iata_code: "TFS",
    icao_code: "GCTS",
    lat: 28.04447,
    lng: -16.57249,
    country_code: "ES",
  },
  {
    name: "Teruel Airport",
    iata_code: "TEV",
    icao_code: "LETL",
    lat: 40.4135,
    lng: -1.21794,
    country_code: "ES",
  },
  {
    name: "Tirviá Heliport",
    iata_code: null,
    icao_code: "LETV",
    lat: 42.518799,
    lng: 1.24231,
    country_code: "ES",
  },
  {
    name: "Tomás Fernández Espada Airfield",
    iata_code: null,
    icao_code: "LETF",
    lat: 36.871793,
    lng: -5.648775,
    country_code: "ES",
  },
  {
    name: "Torozos",
    iata_code: null,
    icao_code: "LETZ",
    lat: 41.78533,
    lng: -4.86436,
    country_code: "ES",
  },
  {
    name: "Torre Picasso Heliport",
    iata_code: null,
    icao_code: "LETS",
    lat: 40.4498291437,
    lng: -3.6931443214,
    country_code: "ES",
  },
  {
    name: "Tortosa Verge de la Cinta Hospital Heliport",
    iata_code: null,
    icao_code: "LETT",
    lat: 40.811292,
    lng: 0.523354,
    country_code: "ES",
  },
  {
    name: "Trebujena",
    iata_code: null,
    icao_code: "LETJ",
    lat: 36.861389,
    lng: -6.140556,
    country_code: "ES",
  },
  {
    name: "Tremp Heliport",
    iata_code: null,
    icao_code: "LETR",
    lat: 42.1693992615,
    lng: 0.8927779794,
    country_code: "ES",
  },
  {
    name: "Ullastrell-Teresa Vilá Heliport",
    iata_code: null,
    icao_code: "LEUL",
    lat: 41.5242996216,
    lng: 1.9715800285,
    country_code: "ES",
  },
  {
    name: "Universitario de Canarias Hospital Heliport",
    iata_code: null,
    icao_code: "GCHU",
    lat: 28.456101,
    lng: -16.291888,
    country_code: "ES",
  },
  {
    name: "Valencia-Betera Air Base",
    iata_code: null,
    icao_code: "LEBT",
    lat: 39.62447,
    lng: -0.472576,
    country_code: "ES",
  },
  {
    name: "Valencia Airport",
    iata_code: "VLC",
    icao_code: "LEVC",
    lat: 39.48931,
    lng: -0.48163,
    country_code: "ES",
  },
  {
    name: "Valladolid Airport",
    iata_code: "VLL",
    icao_code: "LEVD",
    lat: 41.70611,
    lng: -4.85194,
    country_code: "ES",
  },
  {
    name: "VALLADOLID (SUBCENTRO DE COMUNICACIONES DE METEOROLOGIA)",
    iata_code: null,
    icao_code: "LEDM",
    lat: 41.701111,
    lng: 4.85,
    country_code: "ES",
  },
  {
    name: "Vielha Heliport",
    iata_code: null,
    icao_code: "LEVH",
    lat: 42.697126,
    lng: 0.801571,
    country_code: "ES",
  },
  {
    name: "VIELHA (LLEIDA) (HEL)",
    iata_code: null,
    icao_code: "LEVH",
    lat: 42.703333,
    lng: 0.796944,
    country_code: "ES",
  },
  {
    name: "Vigo-Peinador Airport",
    iata_code: "VGO",
    icao_code: "LEVX",
    lat: 42.2318,
    lng: -8.62678,
    country_code: "ES",
  },
  {
    name: "Vilaller Heliport",
    iata_code: null,
    icao_code: "LEVR",
    lat: 42.3046989441,
    lng: 0.7130560279,
    country_code: "ES",
  },
  {
    name: "Villaframil",
    iata_code: null,
    icao_code: "LEVF",
    lat: 43.55245,
    lng: -7.08827,
    country_code: "ES",
  },
  {
    name: "Villahermosa Heliport",
    iata_code: null,
    icao_code: "LEVO",
    lat: 38.750938,
    lng: -2.842076,
    country_code: "ES",
  },
  {
    name: "Viso del Marqués Airport",
    iata_code: null,
    icao_code: "LEVI",
    lat: 38.5055999756,
    lng: -3.4261500835,
    country_code: "ES",
  },
  {
    name: "Vitoria Airport",
    iata_code: "VIT",
    icao_code: "LEVT",
    lat: 42.88284,
    lng: -2.72447,
    country_code: "ES",
  },
  {
    name: "Zaragoza Airport",
    iata_code: "ZAZ",
    icao_code: "LEZG",
    lat: 41.66624,
    lng: -1.04155,
    country_code: "ES",
  },
  {
    name: "Zaragoza United States Air Force Operated Base In Foreign Country",
    iata_code: null,
    icao_code: "LEZA",
    lat: 41.66667,
    lng: -1.05,
    country_code: "ES",
  },
]
