export const exampleAirports = [
  {
    name: "A Coruna Airport",
    iata_code: "LCG",
    icao_code: "LECO",
    lat: 43.30206,
    lng: -8.37726,
    country_code: "ES",
  },
  {
    name: "Ablitas",
    iata_code: null,
    icao_code: "LETU",
    lat: 42.00838,
    lng: -1.62303,
    country_code: "ES",
  },
  {
    name: "Adeje Heliport",
    iata_code: null,
    icao_code: "GCAD",
    lat: 28.124165,
    lng: -16.742906,
    country_code: "ES",
  },
  {
    name: "Adolfo Suarez Madrid-Barajas Airport",
    iata_code: "MAD",
    icao_code: "LEMD",
    lat: 40.49181,
    lng: -3.56948,
    country_code: "ES",
  },
  {
    name: "Aeródromo de Guadalupe",
    iata_code: null,
    icao_code: "LEGU",
    lat: 39.345699,
    lng: -5.19735,
    country_code: "ES",
  },
  {
    name: "Aeródromo de Herrera de Pisuerga",
    iata_code: null,
    icao_code: "LERP",
    lat: 42.5923,
    lng: -4.2902,
    country_code: "ES",
  },
  {
    name: "Aeródromo de los Oteros",
    iata_code: null,
    icao_code: "LEOS",
    lat: 42.333056,
    lng: -5.451944,
    country_code: "ES",
  },
  {
    name: "Aeródromo Requena El Rebollar",
    iata_code: null,
    icao_code: "LERE",
    lat: 39.474701,
    lng: -1.03444,
    country_code: "ES",
  },
  {
    name: "Aeródromo Virgen de La Estrella",
    iata_code: null,
    icao_code: "LEVE",
    lat: 38.4205555556,
    lng: -6.3569444444,
    country_code: "ES",
  },
  {
    name: "Aeroport de Girona - Costa Brava",
    iata_code: "GRO",
    icao_code: "LEGE",
    lat: 41.90097,
    lng: 2.76055,
    country_code: "ES",
  },
]
